name: Client Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    env:
      VUE_APP_APIURL: ${{ secrets.VUE_APP_APIURL }}
    name: Build and Deploy Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Release
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: face-auth.onpy.in
          keep_files: true
      - name: Preview Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: preview/${{ github.event.pull_request.number }}
          cname: face-auth.onpy.in
      - name: Publish
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Client Github Pages Build
          message: |
            Preview avaiable to https://face-auth.onpy.in/preview/${{ github.event.pull_request.number }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Delete Preview
        run: |
          rm -rf preview/${{ github.event.pull_request.number }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          ref: gh-pages
          commit_message: Delete Preview ${{ github.event.pull_request.number }}
